#!/usr/bin/env sh

cd $WORKDIR/LightFTP/Source/Release
gdb -ex run --args afl-fuzz -d -i $AFLNET/tutorials/lightftp/in-ftp -o out-lightftp -N tcp://127.0.0.1/2200 -x $AFLNET/tutorials/lightftp/ftp.dict -P FTP -D 10000 -q 4 -s 4 -E -R -c ./ftpclean.sh ./fftp fftp.conf 2200